python-zk/kazoo

- kazoo/recipe/queue.py
There's a misprint - instead of checking if we're holding the lock, we just checking method like `bool(self.holds_lock)`.
> Proper check if we hold the lock in locking queue

- CHANGES.rst
- kazoo/client.py
- kazoo/hosts.py
- setup.py
Instead of doing customizations for py2/py3 just use
the six module (which is all this module does) to achieve
the same effect but in a more maintained and standard
way.
This uses the six module to do the following:
* Figure out what the best urllib parse is at.
* Figure out and use the byte/string types that six
locates in the client (and adjust the type checks
and exceptions raised to use it); also improves
upon the type errors raised to hopefully be more
meaningful.
There are still a few leftover but hopefully those can
be adjusted in the future (and in another patch series).
> Use six for *some of* py3/py2 compat tweaks

- kazoo/handlers/gevent.py
- kazoo/handlers/utils.py
Avoid late importing modules that we can just import at the
normal top of file time (late importing doesn't seem to add
any benefit and IMHO makes the code harder to understand).
Also order more of the imports to follow the standards where
they are typically ordered alphabetically (with stdlib modules
being before other modules and the library itself being last).
> Tweak some of the import(s)

- kazoo/client.py
- kazoo/handlers/eventlet.py
- kazoo/handlers/threading.py
- kazoo/handlers/utils.py
- kazoo/protocol/connection.py
- kazoo/python2atexit.py
- kazoo/testing/harness.py
- kazoo/tests/test_connection.py
- kazoo/tests/test_interrupt.py
Fixes quite a few of the flake8 compliants that it was raising:
* Quite a few of unused module imports.
* Line lengths to long.
* Not enough newlines around functions.
* Lines with just whitespace.
> Fix a bunch of flake8 reported issues

- kazoo/handlers/eventlet.py
Use the right ``atexit`` routines (that work better in py2/py3).
> Use the helper python2atexit for atexit routines

- CHANGES.rst
- kazoo/recipe/lock.py
- kazoo/tests/test_lock.py
Instead of having acquire be re-entrant but release remove
the lock immediately we should just not be re-entrant at
all since the current implemetnation is mostly broken in
the first place (especially when the inner release will destroy
other acquires...).
Fixes #291
> Have the lock recipe no longer be sorta re-entrant

- CHANGES.rst
- docs/api.rst
- docs/api/recipe/lease.rst
- kazoo/client.py
- kazoo/recipe/lease.py
- kazoo/tests/test_lease.py
This is in production at Spotify for monitoring scripts.
> Add lease recipe.

- CHANGES.rst
- kazoo/hosts.py
- kazoo/tests/test_client.py
Here's an example of crashing with a bad hosts string:
```
In [1]: from kazoo.client import KazooClient
In [2]: k = KazooClient("/nosuchhost/a")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-25a91e9f619d> in <module>()
----> 1 k = KazooClient("/nosuchhost/a")
/usr/lib/python2.7/site-packages/kazoo-2.0.1dev-py2.7.egg/kazoo/client.pyc in __init__(self, hosts, timeout, client_id, handler, default_acl, auth_data, read_only, randomize_hosts, connection_retry, command_retry, logger, **kwargs)
181         self.hosts = None
182         self.chroot = None
--> 183         self.set_hosts(hosts)
184 
185         # Curator like simplified state tracking, and listeners for …
```
> Don't crash when the hosts strings is bogus

- CHANGES.rst
- kazoo/recipe/lock.py
- kazoo/tests/test_lock.py
Instead of having it raise a runtime error have the calling
thread block until the lock has been released (typically
by some other thread). This more closely matches the existing
and (assumingly) expected behavior of locks.
> Have the lock reentrancy behave like threading.lock

- CHANGES.rst
- kazoo/client.py
- kazoo/tests/test_client.py
Due to the apparent flakiness of the four-letter commands
we need to add a set of retries to the fetching of the
server version to handle getting partial or truncated values
back from it.
This adds a default of 4 tries (1 + 3 retries) to the server
version code so that if a partial value is returned (or no
server version at all) that the code will try again, if none
can be fetched in 4 tries; then none is returned to signify
this failure.
Fixes issue #274
> Add retries to server_version() fetch

- kazoo/protocol/connection.py
If the client disconnects with the ping_outstanding event set, when it
reconnects the first timeout will cause a "dropped" heartbeat, and make
the library reconnect yet again.
> Re-set the ping_outstanding event before connecting

- kazoo/handlers/threading.py
Instead of creating daemon threads in two places, both
using the same code, just have the `_create_thread_worker`
method call into the spawn method to delegate to it to create
a daemon thread.
> Use the spawn method when creating thread handler workers

- kazoo/testing/harness.py
Instead of using ``atexit``, use the compat. layer that makes sure the py2.x versions of atexit function properly.
> Use the compat layer for atexit functionality

- kazoo/recipe/lock.py
The semaphore should be passing the blocking argument to the
underlying lock that is used (so it is non-blocking as well) and
it should also be passing the timeout as well.
The non-blocking result should also not add a watch that will
later attempt to get the least (another call to acquire should be
used instead, or the blocking mode should be used instead).
> Fix semaphore usage

- kazoo/recipe/lock.py
- kazoo/testing/common.py
- kazoo/testing/harness.py
- kazoo/tests/test_lock.py
- Adds checks to make sure that on each stop that
is called that the zookeeper process has exited cleanly with
a zero error code (and log if this doesn't happen)
- Log the started programs
- Track all created clients (and stop them on teardown)
- Track threads made in lock/sempahore tests and clean them up
> Do cleanup in a more more robust manner

- .gitignore
- .travis.yml
- Makefile
- ensure-zookeeper-env.sh
This moves the Zookeeper install from `bin/zookeeper-3.4.6` to `zookeeper/3.4.6` to make it easier to cache it.
In the new sudo-less environment you can't use `sudo apt-get` anymore. This might result in failing to installed gevent 0.13.8, gevent 1.0.x includes a copy of libev inside the tar.gz, so it should build fine.
First test to see if the caches get populated...
> Make use of the new travis-ci caching mechanism.

- kazoo/python2atexit.py
A small issue I've encountered during shutdown.
> replacing sys.stderr(...) with sys.stderr.write(...)

- .travis.yml
- requirements_eventlet.txt
- requirements_gevent.txt
- tox.ini
Ensure that we have specific virtualenvs listed in tox that install the
desired gevent and eventlet versions and ensure that the
``.travis.yml`` file references them for usage.
This also adds gevent (with no version restriction) to the py27, py26
builds (with postfix ``-gevent``) and also adds eventlet specific virtualenvs
(with postfix ``-eventlet``) for making sure that eventlet and gevent
continues to work.
Fixes issue #328
> Fix up tox envs and their usage in travis

- kazoo/client.py
The rest of the type error exceptions follow a common style
so this adjusts these new type error exceptions to follow
this style.
> Reformat messages in type error exceptions strings in reconfig

- CHANGES.rst
- setup.py
Version 2.1.1 was never released (due to **repeated** travis build errors)
so we can remove it from being a version number and go directly
to 2.2 (and collapse the CHANGES.rst to account for that).
> Bump version up to 2.2

- README.rst
The pypip.in site has not been working for a few weeks
now so move to a badge site that is more reliable.
> Move badges from pypip.in to shields.io

- kazoo/testing/common.py
If I use `destroy` or `reset` after starting the cluster, the error occurs at exit, so I have to restart the closed cluster before exit just to avoid the error.
> ignore error when removing directory

- kazoo/recipe/counter.py
- kazoo/recipe/election.py
- kazoo/recipe/lease.py
- kazoo/recipe/lock.py
- kazoo/recipe/partitioner.py
Fix the recipe examples, so they actually work by connecting
to ZooKeeper. Without start() they just hang and can't be killed.
> Fix examples in recipes

- kazoo/testing/common.py
It's already imported at the top of the file.
> Remove redundant shutil import from test harness code

- MANIFEST.in
Seems like people would like the docs included
in the package output, so ensure we pick them
up.
Fixes issue #379
> Include docs in the built packages

- CONTRIBUTING.rst
From commit 4db81cf00d4f0b6ba522244f69fa5878d15b07cc, the make
target 'zookeeper' was removed and the tox is needed to run
'make test'.
> Remove the notation about 'make zookeeper'.

- kazoo/recipe/lock.py
(Fixes https://github.com/python-zk/kazoo/issues/288)
- Make sure that self.node always exists.
- Use _best_effort_cleanup() instead of _delete_node() when we didn't
get the lock.
- Make RetryFailedError use the existing cleanup code.
- Make _best_effort_cleanup use self.node if it's set, and fall back to
_find_node otherwise.
> Fix handling of retry failures in Lock.acquire

- kazoo/handlers/threading.py
- kazoo/handlers/utils.py
This is a followup to #250
This PR includes 2 patches both fixing more interrupt issues. Basically this is an upstream issue (in python-- http://bugs.python.org/issue20611).
The first patch changes my previous fix (#250) from raising a timeout to retrying-- the issue we see is that the rest of the kazoo code assumes that a timeout is a timeout (which is reasonable). So instead of reworking all timeouts within kazoo, we can simply retry.
The second patch handles the same during connection setup.
> System call interrupts

- kazoo/recipe/watchers.py
- kazoo/tests/test_watchers.py
- tox.ini
This implementation resolves the "NoNodeError" while watching children.
Fix #149.
> Close the ChildrenWatch if the node doesn't exist. 

- setup.cfg
In order to build a python 2 and 3 universal wheel the bdist_wheel configuration must be added to setup.cfg.
> Build python 2 and 3 universal wheels

- kazoo/protocol/connection.py
fix xid out of range (-2147483648 <= number <= 2147483647)
> fix xid out of range

- requirements_gevent.txt
Gevent >= 1.1 is not py2.6 compat; so use the requirements
python version restriction mechanism to restrict what
versions work on older versions of python.
> Restrict gevent for older versions and newer versions

- kazoo/client.py
- kazoo/protocol/connection.py
- kazoo/protocol/serialization.py
- kazoo/tests/test_client.py
Basic plumbing to support resetting watches upon recovering a session (as done by the Java implementation).
Given this breaks the current behaviour, it should be made optional. I'll circle back with that added in. Comments welcomed! 
Fixes #218 
Signed-off-by: Raul Gutierrez S rgs@itevenworks.net
> [RFC] Support SetWatches and watch restoration

- kazoo/recipe/watchers.py
If the func passed to DataWatcher or ChildrenWatch is bound to an object it
will keep a reference to the object around which could prevent it from getting
garbage collected.
> Fix potential leak in DataWatch and ChildrenWatch

- kazoo/retry.py
The previous max_delay interval of 1 hour seems far too high for a distributed locking system given that the initial retry time is 100ms.
> Set default max_delay to one minute

- kazoo/client.py
- kazoo/protocol/states.py
- kazoo/recipe/watchers.py
- kazoo/tests/test_client.py
This behavior matches the reference implementation
Introduces a NONE event
> Ensure pending watches are not dropped when connection is lost

- debian/control
- setup.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- kazoo/recipe/counter.py
- kazoo/tests/test_counter.py
This commit extends the `Counter` API with the `pre_value` and
`post_value` attributes. These attributes are set when a counter
is changed. Previously, if the counter was modified concurrently,
it was not possible to access the exact value to which the counter
was set after a successful increment or decrement.
> Counter: expose the previous and changed values.

- kazoo/protocol/connection.py
- kazoo/tests/test_connection.py
This commit fixes https://github.com/python-zk/kazoo/issues/229  by throwing the runtime exception into the dequeued `async_result`. It will end the waiting of user threading.
But this commit doesn't fix the xids mismatch itself (https://github.com/python-zk/kazoo/issues/254). The unordered xids may caused by a bug from the ZooKeeper server side, such as the official issues [ZOOKEEPER-1863](https://issues.apache.org/jira/browse/ZOOKEEPER-1863) described.
> Fix the client.add_auth hangs by xids mismatch.

- kazoo/recipe/lock.py
Issue #429 fix
fix deadlock in nonblocking semaphore acquiring by doing semaphore inner lock release for every lock acquiring attempt
> fix deadlock in nonblocking semaphore acquiring

- MANIFEST.in
Looks like the .rst files got converted to .md, but MANIFEST.in wasn't
updated.  This also fixes the sdist, since setup.py expects README.md &
CONTRIBUTING.md to be in the source tarball.
Closes #437
> chore: update MANIFEST.in to reflect changes to filenames

- kazoo/recipe/queue.py
The second clause of the conditional (checking if the lock is held) will always evaluate to True.
> Add missed parens to function call.

- kazoo/handlers/threading.py
- kazoo/tests/test_threading_handler.py
Here's my take on the fd > 1023 issue. I'm open to suggestions for the unit test.
Major points:
When epoll is available, and the highest fd in use is > 1023, route through epoll.
Otherwise, use the existing select() behavior so by and large nothing changes.
closes #266
closes #171
> Use epoll when available to support fds > 1023

- kazoo/hosts.py
- kazoo/tests/test_hosts.py
> KazooClient hosts list should accept a list of multiple endpoints.

- kazoo/client.py
- kazoo/protocol/connection.py
- kazoo/protocol/serialization.py
- kazoo/tests/test_client.py
PR #305 introduced a feature to restore watches on reconnect.
Unfortunately this introduced RuntimeError's under various cases, so
reverting it is necessary.
> fix(core): revert PR #305 SetWatches which caused RuntimeError

- docs/install.rst
- setup.cfg
Everyone uses `pip` these days.
> chore: remove `easy_install` instructions

- tox.ini
Looks like removing this was overlooked in https://github.com/python-zk/kazoo/commit/2faba9ff3bdeff151ac6c922bf65b2dcf9c7bd7b
> chore: remove python 3.3 from tox

- .gitignore
- .travis.yml
- Makefile
- kazoo/tests/test_build.py
This is a continuation of #467.
I needed all those fixes in order to get `make` run again on my mac.
> chore: stop bundling virtualenv and assorted fixes

- requirements_gevent.txt
We dropped python 2.6 support a while ago, so no need for the added complexity here.
> Drop python 2.6 compatible gevent

- kazoo/recipe/partitioner.py
- kazoo/recipe/watchers.py
- kazoo/tests/test_gevent_handler.py
- kazoo/tests/test_threading_handler.py
The use of "async" and "await" as variable are deprecated in Python 3.7. This patch removes the use of "async" (there is no usage of "await" to fix).
Closes #455
> fix: Remove use of "async" as a variable

- docs/index.rst
Gevent support < 1.2 was dropped in https://github.com/python-zk/kazoo/commit/2e8dcd3836d01640f07e8de911cdfb3639f97d20 (and further tweaked in https://github.com/python-zk/kazoo/pull/483).
Travis already tests the Zookeeper 3.5 series.
> docs: Correctly document supported versions

- requirements_gevent.txt
- setup.py
Python 2.6 support was dropped in 1.2, so https://github.com/python-zk/kazoo/commit/2e8dcd3836d01640f07e8de911cdfb3639f97d20 simplified the dependency graph to require `gevent>1.1`. However, bugfix releases to the 1.1 series (1.1.1, etc) will satisfy this requirement, so we should actually be requiring `gevent >= 1.2`
> fix: need gevent >= 1.2, not > 1.1

- kazoo/handlers/utils.py
- kazoo/tests/test_threading_handler.py
> fix(core): resolve race in IAsyncResult.wait()

- kazoo/client.py
We instrument calls to async functions, but are unable to get the watch parameter because it is not being passed as part of kwargs. This will allow us to capture the watch parameter.
> fix: Pass watch as keyword arg instead of positional arg

- kazoo/recipe/lock.py
Using exists will register a creation, as well as update and deletion
watch on the given node. This introduces a race, where the predecessor
node can get deleted between the call to getChildren() and exists().
If that happens, the exists() sets a create watch on a node that will
never be created, leaks a create watch.
> fix (recipe): don't set creation watch on lock predecessor node

- kazoo/handlers/eventlet.py
- kazoo/handlers/gevent.py
- kazoo/recipe/cache.py
- kazoo/tests/test_cache.py
This pull request fixes some edge bugs which were found in our production, and improves performance by approaching the behaviors of Apache Curator:
1. The new TreeCache uses a standalone background queue instead of using the Kazoo handler's one.
2. The new TreeCache ignores unknown exceptions of async operations instead of crashing.
3. The tree refreshing operations send `\0` to a pipe or socketpair for waking up the connection routine. Those operations will block the session watcher callback and has been moved to the background queue.
Thanks for @mozillazg for detecting those issues.
> Fix a batch of known issues of TreeCache recipe

- kazoo/recipe/lock.py
- kazoo/tests/test_lock.py
Right now if the program taking the lock exits, the lock is also
released as the zk node is ephemeral. In some usecases its desirable to
make the lock release explicit. For example, in scripting multiple
programs that contend for a lock, or purposeful failing lock acquirers
to detect issues.
The ephemeral flag in acquire() allows for this behavior.
> Allow non ephemeral locking without implicit release

- kazoo/handlers/utils.py
- kazoo/tests/test_threading_handler.py
Due to the use of unbound lambdas in AsyncResult, multiple callbacks
wouldn't actually get called. it would only call the final callback N
times, where N is the number of registered callbacks.
> fix(core): Correctly fire multiple callbacks

- kazoo/client.py
- kazoo/handlers/utils.py
- kazoo/protocol/connection.py
This PR adds SSL support for Zookeeper connection. I took back the commit from https://github.com/python-zk/kazoo/pull/494
Usage is:
```
from kazoo.client import KazooClient
zk = KazooClient(hosts='172.20.0.2:2281', use_ssl=True, keyfile='/path/to/key.pem', certfile='/path/to/cert.pem', ca='/path/to/ca.pem', keyfile_password='password')
zk.start()
...
```
When playing with self signed certificate, it is possible to bypass certs verification using the paramater 'verify_certs':
```
from kazoo.client import KazooClient
zk = KazooClient(hosts='172.20.0.2:2281', use_ssl=True, keyfile='/path/to/key.pem', certfile='/path/to/cert.pem', keyfile_password='password', verify_certs=False)
zk.start()
...
```
I am not sure on how to add tests since I need to add a specific SSL configuration for only …
> feat(core): Added SSL support

- kazoo/client.py
- kazoo/retry.py
The previous implementation would add a fixed amount of jitter around
the calculated back-off time. Retry attempts were thus clustered
around the exponentially spaced backoff points.
This patch does exponential backoff but uniformly spreads the retries
over an interval [0, backoff**attempt]
The following graphs show the connection rate/s when trying to open 20k new connections
to ZK. Each client was configured with, backoff=2, delay=10 and max_delay=180. The ZK in question is rate-limited and that explains the ceiling you see on the second graph. 
**Old Jitter**
The connections attempts come in herds after the current delay interval has passed.
After over 30mins only about 10k connections had been established and that is where I cut-off the graph.
**Uniform Jitter**
The connection …
> KazooRetry: Do uniform jitter over the whole backoff interval

- kazoo/client.py
- kazoo/protocol/connection.py
- kazoo/protocol/serialization.py
- kazoo/testing/common.py
- kazoo/tests/test_client.py
- requirements.txt
- setup.py
This PR adds support for **DIGEST-MD5** SASL authentification to Zookeeper.
Usage is as same as before except that we can now use the 'sasl' mechanism:
```
from kazoo.client import KazooClient
zk = KazooClient(hosts='172.20.0.2:2181', auth_data=[('sasl', 'user:password')])
zk.start()
...
```
I mainly followed [Zookeeper's client-server mutual authentication](https://cwiki.apache.org/confluence/display/ZOOKEEPER/Client-Server+mutual+authentication) documentation for this implementation.
It uses the [pure-sasl library](https://github.com/thobbs/pure-sasl) to manage the SASL challenge. It is a very well documented library to use for SASL authentification and can also be used if we want to add a **GSSAPI** support for Zookeeper.
Some tests also have been added.
Thank you
Stephen
> feat(core): Added SASL DIGEST-MD5 support

- kazoo/protocol/connection.py
It is possible to race between processing a new addAuth request(which updates the client.auth_data set) and iterating through it during reconnect. To avoid set changes during iteration, make a copy.
> fix(core): Use a copy of auth data when reconnecting

- docs/index.rst
The link is currently broken. Replaced it with the current programmers guide link.
> docs(core): fix broken zookeeper programmers guide link

- .travis.yml
- kazoo/testing/common.py
- kazoo/testing/harness.py
- kazoo/tests/test_client.py
I upgraded Zookeeper version to 3.5.4-beta. Some changes occured since the 3.5.2-alpha used before :
- reconfig needs to be explicitely activated in zookeeper configuration
- reconfig needs to be used with superuser
- envi command must be added to whitelist
I added a test to check that a NoAuthError is obtained when trying to use Reconfig without superuser. I corrected Reconfig's tests to use superuser auth. I modified the testing/common.py file to add the new parameters to zookeeper server.
> feat(tests): bump zookeper version to 3.5.4-beta

- kazoo/protocol/connection.py
> fix(core): get_children with include_data=True uses GetChildren2 types

- README.md
Pypi quit offering download stats, so remove this broken badge.
> docs: remove broken downloads badge

- CHANGES.md
- setup.py
While working on https://github.com/python-zk/kazoo/pull/528, I realized that the docs don't actually render correctly on [PyPi](https://pypi.org/project/kazoo/2.5.0/). This is because PyPi defaults to assuming a `.rst` file ( as specified in the [FAQs](https://pypi.org/help/#description-content-type)) and our readme is `.md`
PyPi pointed to the [python packaging guide](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata) which explains to include the `long_description_content_type="text/markdown",` parameter in your setup for proper packaging. On testing with `twine` as specified in the python packaging guide, I got an error `Unexpected indentation line 270` which was fixed by unindenting the two lines below. 
Steps to test …
> docs: specify description type for pypi to render correctly

- README.md
Currently the badges just open a static image of the badges. This makes it so that it opens the actual links to latest travis build and PyPi instead.
[Updated README](https://github.com/python-zk/kazoo/blob/0dfa2670393c6878896bab630825664704c9efe8/README.md).
For context: https://docs.travis-ci.com/user/status-images/ this is where I got the Travis link button command. 
And https://badge.fury.io/for/py/kazoo for the PyPi badge.
**Update**: Moved to using shields.io like it was before instead of badge.fury. Here's the [README](https://github.com/python-zk/kazoo/blob/c79a152668e166321d849aa3ed749264f3eb1b29/README.md) with shields.io.
> docs: make badges link to travis and pypi

- docs/Makefile
```bash
> make
Please use `make <target>' where <target> is one of
changes                         to make an overview of all changed/added/deprecated items
devhelp                         to make HTML files and a Devhelp project
dirhtml                         to make HTML files named index.html in directories
doctest                         to run all doctests embedded in the documentation (if enabled)
epub                            to make an epub
gettext                         to make PO message catalogs
html                            to make standalone HTML files
htmlhelp                        to make HTML files and a HTML help project
info                            to make Texinfo files and run them through makeinfo
json                            to make JSON files
latex …
```
> self-documenting make targets

- kazoo/handlers/utils.py
- kazoo/tests/test_utils.py
Previously, a gap between calls to `time.time()` could lead to a situation where the current time was less than `end` during the `while` condition, but it was greater than `end` when assigning a value to `timeout_at`.
This is the same issue describe in https://github.com/python-zk/kazoo/pull/518, but the fix is slightly different. It avoids a redundant call to `time.time()`. I've also included a unit test that exhibits the problem when run without the fix.
> fix: ensure timeout argument is nonnegative

- kazoo/handlers/eventlet.py
- kazoo/handlers/gevent.py
- kazoo/handlers/threading.py
- kazoo/recipe/cache.py
- kazoo/tests/test_cache.py
- requirements.txt
- setup.py
The current implementation of TreeCache recipe could not be closed completely because some unexpected references:
1. The registered znode event watchers hold the reference of instancemethod which are bound with `TreeNode` instances
2. The background threads in connection handler keep last reference when they are idle
This pull request fixes those memory leak problems, and verifies that by using `objgraph` in test.
We could guarantee all closed `TreeCache` will be eventually released now. (not immediately since the cycle reference between `TreeNode` and `TreeCache` must be resolved by mark-swap GC of Python)
> fix(recipe): No more memory leak once TreeCache was closed

- kazoo/protocol/connection.py
In the case of a zookeeper server under pressure, it will typically try to maintain the quorum rather than handling client requests. In this kind of case, the quorum is maintained, the connection works, but the client is frozen there.
Retrying after a shorter timeout means we can reconnect to another server before losing the session altogether.
> Reduce timeout for the first Connect() request

- kazoo/recipe/watchers.py
- kazoo/tests/test_watchers.py
Remove session watcher from the listener when ChildrenWatch was stopped
> fix(recipe):No more memory leak when ChildrenWatch was stopped

- kazoo/retry.py
Accept kazoo<=2.5.0 KazooRetry 'max_jitter' argument and display a
warning for backward compatibility.
See #544
> fix(regression): Support deprecated KazooRetry argument

- kazoo/handlers/gevent.py
- kazoo/handlers/threading.py
- kazoo/handlers/utils.py
- kazoo/tests/test_client.py
Hi!
I'm using kazoo in a work-related project and sometimes our tests are leaving zombie threads that are blocked in `self._condition.wait(timeout)` from `AsyncResult:get`. 
After some digging it looks like the problem occurs when we start a KazooClient, try to make an operation on it like a path creation and then stop it fast. In this case, the callbacks of the `AsyncResult` may not be called if `AsyncResult:set`/`AsyncResult:set_exception` are called just after the client is stopped. As I said it might not happen too often for most people but for us it's like in 10% of the test runs and it's slows  down our development pipeline. I've made a custom `AyncResult` class in our project that modifies a bit the behavior and seems to fix the issue for us but maybe you guys would also consider …
> fix(handlers): make AsyncResult call all registered callbacks instantly if the handler has stopped running

- kazoo/recipe/counter.py
- kazoo/tests/test_counter.py
this patch allows java clients using curator's SharedCount recipe
and python clients using kazoo's Counter recipe to read and
write from the same path without receiving type errors.
example use:
`counter = zk.Counter("/curator", support_curator=True)`
`counter += 2`
`counter -= 1`
`counter.value == 1`
`counter.pre_value == 2`
`counter.post_value == 1`
Closes #558
> feat(recipe): add support for curator SharedCount recipe

- kazoo/handlers/utils.py
It would be a great thing to set context options and ciphers to provide better security.
> Extend create_tcp_connection utility

- kazoo/recipe/lock.py
fix if znode is None
```
File "/home/tests/kazoo/recipe/lock.py", line 341, in contenders
contenders.append(data.decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'
```
> fix(recipe): crash if None in znode

- kazoo/client.py
> Closed states instead of lost states

- .travis.yml
- ensure-zookeeper-env.sh
- kazoo/testing/common.py
- kazoo/tests/test_client.py
- setup.py
- tox.ini
Fixes https://github.com/python-zk/kazoo/issues/552
> Add python 3.7 to CI and bump ZK versions to latests

- kazoo/client.py
When connection attempts fail repeatedly (e.g. all ZK servers are
unavailable), eventually the socketpair in the ConnectionHandler fills
up, and the Client gets stuck trying to write a single byte to the
socketpair.
Avoid this by ensuring we close the socketpair on a failed connection
attempt.
> fix(core): when connection fails, close the ConnectionHandler (#577)

- kazoo/security.py
- kazoo/testing/common.py
`make_digest_acl_credential` assumes `UTF-8`, but ZooKeeper decodes digest auth packets using the JVM's default "charset"—which depends on the environment (e.g., `ISO-8859-1` if no locale is present).
This patch defines the system property which makes the JVM hosting ZooKeeper default to `UTF-8`, independently of the locale.
> fix(tests): specify -Dfile.encoding=UTF-8 when starting the ZK JVM

- kazoo/client.py
- kazoo/protocol/serialization.py
- kazoo/tests/test_client.py
Add support for `Create2` opcode (create returns ZkStat along side the path after a successful node creation).
> feat(core): Add create2 support

- docs/api/client.rst
- kazoo/client.py
- kazoo/tests/test_client.py
With this patch, requests issued while the client is in the `CONNECTING` state get queued instead of raising a misleading `SessionExpiredError`.
This fixes https://github.com/python-zk/kazoo/issues/374, and brings Kazoo more in line with the Java and C clients.
See the `kazoo.client.KazooClient.state` documentation as well as these discussions for more details:
* https://github.com/python-zk/kazoo/pull/570#issuecomment-554798550
* https://github.com/python-zk/kazoo/pull/583#issuecomment-586422386
This "v2" is a respin of https://github.com/python-zk/kazoo/pull/583 which only includes the fix for https://github.com/python-zk/kazoo/issues/374.
A few notes:
(Feel free to suggest a better place for that documentation.  I haven't updated `CHANGES.md` as that seems to be done at release time.)
> fix(core): allow requests to be queued in CONNECTING state (#374) [v2]

- .flake8
- .hound.yml
- kazoo/recipe/lock.py
- kazoo/tests/test_lock.py
Go client uses a different prefix.
Ref:
* https://github.com/python-zk/kazoo/issues/548
* https://github.com/go-zookeeper/zk/pull/19
> [lock] interoperate with Go client

- kazoo/protocol/serialization.py
As of Python 3.8, "is" with a literal is a syntax warning and may become an error in the future. Kazoo ran afoul of this in a few places.
Fixes
```
/kazoo-2.7.0-py3.8.egg/kazoo/protocol/serialization.py:114: SyntaxWarning: "is" with a literal. Did you mean "=="?
```
> Fix '"is" with a literal' syntax warnings

- .travis.yml
Relates to https://github.com/python-zk/kazoo/issues/607
- Test Kazoo with CPython 2.7, CPython 3.7 and CPython 3.8.
- Deploy new Kazoo version only on CPython 3.8 job success.
> feat(tests): add Python 3.8 and remove Python 3.6 from the testing suite

- kazoo/handlers/threading.py
This is a faster and more idiomatic way of using `itertools.chain`. Instead of computing all the items in the iterable and storing them in memory, they are computed one-by-one and never stored as a huge list. This can save on both runtime and memory space.
> Use chain.from_iterable in threading.py

- .travis.yml
- Makefile
- tox.ini
By dropping py2.7 and pypy, we drop the last of the py2.x syntax from our tests matrix
- Tests are now only run only on py37, py38 and pypy3.
- All py versions run all tests with gevent and sasl.
- Bumped Zookeeper to 3.5.8.
- Update .travis.yml definition per warnings, only syntax refresh.
> chore(core): Update matrix: add pypy3, drop py27

- kazoo/protocol/connection.py
This adds a simple recovery path in case an SSL connection receives
an SSL_WANT_READ or WRITE error.  Either error can occur while
reading or writing.  The error indicates that the underlying
operation should be retried after the socket is once again readable
or writable (per the error code).
Fixes #618
> Handle SSL_WANT_READ/WRITE errors

- kazoo/protocol/connection.py
Without this patch, a single select event is processed by iteration in the `ConnectionHandler` event loop.
In a scenario where the client issues a large number of async requests with an important amplification factor, e.g. `get_children_async` on a large node, it is possible for the 'select' operation to almost always return a "response ready" socket—as the server is often able to
process, serialize and ship a new reponse while Kazoo processes the previous one.
That response socket often (always?) ends up at the beginning of the list returned by `select`.
As only `select_result[0]` is processed in the loop, this can cause the client to ignore the "request ready" FD for a long time, during which no requests or pings are sent.
In effect, asynchronously "browsing" a large tree of nodes can …
> fix(core): do not allow responses to choke request and ping processing

- kazoo/protocol/connection.py
Fixes #
Zookeeper is running from Docker containers and the service being resolved using Consul. When there's a network issue, the call to `socket.getaddrinfo` in method `_expand_client_hosts` causing it to return the error `Cannot resolve .. [Errno -2] Name or service not known`. This is causing retry to throwback `STOP_CONNECTING` and it stops retrying as result.
Change: Raise `ForceRetryError` if method `_expand_client_hosts` returns empty host/ports and `client.hosts` has only one host to resolve.
```
if len(host_ports) == 0:
if len(self.client.hosts) == 1:
raise ForceRetryError('Reconnecting')
return STOP_CONNECTING
```
n/a
> Cannot resolve .. [Errno -2] Name or service not known

- kazoo/recipe/queue.py
There is a small typo in kazoo/recipe/queue.py.
Should read `until` rather than `untill`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, untill -> until

- .github/workflows/release.yml
- .github/workflows/testing.yml
Current configuration of Github Actions only trigger on push on the repo, but not on pull requets, which is kind of limited.
- trigger GA on push to master and release/* branches
- trigger GA on pull request with master or release/* branches as destination
Nah
> chore(ci): better specify how to trigger Github Actions

- kazoo/recipe/lock.py
- kazoo/recipe/queue.py
- kazoo/testing/harness.py
- kazoo/tests/test_lock.py
Fix deprecation warning emitted when calling `threading.Event.isSet`
Reasoning:
- `is_set` is supported since Python2.6 (https://docs.python.org/2.7/library/threading.html)
- Starting from Python3.5 docs the `isSet` spelling is not even mentioned anymore (https://docs.python.org/3.5/library/threading.html)
- Python3.10 will give a deprecation warning when the `isSet` spelling is used (https://docs.python.org/3.10/library/threading.html)
- just use is_set over isSet
- only for users of python version below 2.6; python2.5 is not supported according to setup.py
> fix(recipe): fix deprecation warning from threading.Event

- .github/workflows/release.yml
- .github/workflows/testing.yml
- constraints.txt
- kazoo/testing/common.py
- kazoo/testing/harness.py
- kazoo/tests/conftest.py
- kazoo/tests/test__connection.py
- kazoo/tests/test_sasl.py
- setup.cfg
Make sure the lib is working with Python 3.10 and the latest ZK versions (3.5.10, 3.6.3, 3.7.1)
- add Python 3.10 in matrix testing
- change ZK 3.5.8 to ZK 3.5.10 in matrix testing
- add ZK 3.6.3 in matrix testing
- add ZK 3.7.1 in matrix testing
- better discover .jar files when building the classpath (could be better though)
- rename `test_connection.py` to `test__connection.py` to get it done first (poor way to try to get it less flaky, I confess) and deactivate `fail-fast` feature in GA to get the tests' flakiness less painful
- add `conftest.py` to give a way to get ZK logs when test fails (but needs the -s flag in pytest)
- add ZK local session configuration required to get the read only test working for ZK 3.7
- added Python 3.9 and Python 3.10 to `setup.cfg`
No
> chore(ci): testing with Python3.10 and ZK 3.5.10, 3.6.3, 3.7.1

- README.md
This is to reflect the updated CI pipeline used for the repo
Badge is out of date, and it currently shows a misleading Build: Failing status
- update badge to get status from latest testing workflow on master
Nope
> docs: Replace build badge from Travis to Actions

- kazoo/recipe/lock.py
Fixes #605
Not needed per se, but removes unnecessary complexity from the lock acquiring code
- use timeout parameter from the lock object instead of reimplementing timeout
- rename `self._lock` to `self._thread_lock` (suggestions encouraged), as having a lock inside a lock made this hard to parse
- ...
Nope
> refactor: Use native Lock timeout instead of reimplementing

- kazoo/recipe/cache.py
Fixes #680 
`os.path.join` doesWindows path joining on Windows resulting in bad zookeeper paths
- use the existing path joining method in `kazoo.protocol.paths` instead of `os.path.join`.
No.
> recipe(cache): Use protocol.paths.join instead of os.path.join

- .github/workflows/testing.yml
- tox.ini
tox-wheel is a deprecated package now that tox 4.x includes wheel support.
When this issue occurs, you may see an error message similar to:
```
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/tox_wheel/plugin.py", line 6, in <module>
import py
ModuleNotFoundError: No module named 'py'
Error: Process completed with exit code 1.
```
- remove dependency on tox-wheel
- use tox 4.x
No. Build time changes only.
> chore: migrate to tox 4.x

- .github/dependabot.yml
I noticed some of our GitHub action workflows are throwing deprecation warnings...
Let's have Dependbot open PR's to bump them whenever they're outdated.
We could also enable it for watching our Python deps, but that may be more controversial, so that can be done as a follow-on PR if there's interest.
> Ask Dependabot to bump actions

- .github/workflows/testing.yml
- pyproject.toml
- setup.cfg
- tox.ini
This is intended to be a lightweight version of https://github.com/python-zk/kazoo/pull/684. Rather than add types to everything in one shot, support for typing could be added to the build only. Python code typing could be incrementally added in future smaller/targeted PRs.
The changes in https://github.com/python-zk/kazoo/pull/684 are still useful. This is just an effort to split it up to make it easier to understand.
The method used here follows the same pattern that SQLAlchemy has been using to add types. For an example, see https://github.com/sqlalchemy/sqlalchemy/pull/9039/files and note the removal of the `# mypy: ignore-errors` comment to incrementally add types.
- Add mypy configuration to the build to allow for incremental addition of type annotations.
No. This PR will only …
> chore: add mypy to the build

- kazoo/handlers/utils.py
Prior to this commit python would produce these warnings when using kazoo with ssl:
```
/path/to/venv/lib/python3.11/site-packages/kazoo/handlers/utils.py:225: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
```
The reason for this is that `ssl.PROTOCOL_SSLv23` is an alias for `ssl.PROTOCOL_TLS` and `ssl.PROTOCOL_TLS` is deprecated since Python 3.10.
`ssl.PROTOCOL_TLS` was replaced with `ssl.PROTOCOL_TLS_CLIENT` and `ssl.PROTOCOL_TLS_SERVER`. In kazoo's case we switch to `ssl.PROTOCOL_TLS_CLIENT` as kazoo is acting as an ssl client to zookeeper servers.
There are a few things to note. `PROTOCOL_TLS_CLIENT` enables `context.check_hostname`. We explicitly set this to False as this is required to set `ssl.CHECK_NONE` which kazoo supports, and …
> Cleanup SSL deprecation warnings under Python 3.10 and newer

- constraints.txt
- kazoo/tests/test__connection.py
- kazoo/tests/test_cache.py
- kazoo/tests/test_client.py
- kazoo/tests/test_lock.py
- kazoo/tests/test_partitioner.py
- kazoo/tests/test_threading_handler.py
- kazoo/tests/test_utils.py
- setup.cfg
It's now part of the Python stdlib since `3.3`.
So no need to specify it.
> No need to specify `mock`

- kazoo/protocol/connection.py
- kazoo/tests/test_client.py
In case of AUTH_FAILED in the zk-loop thread it will call client._session_callback which will reset the queue.
However another thread can add to this queue CloseInstance event, and if the _session_callback() will be called after CloseInstance was added to the queue, then stop() will never return (and zk-loop will endlessly spin).
Here is how it looks like with addititional logging:
39: [ Thread-3 (zk_loop) ] INFO: client.py:568: _session_callback: Zookeeper session closed, state: AUTH_FAILED
39: [ MainThread ] Level 5: client.py:721: stop: Sending CloseInstance
39: [ Thread-3 (zk_loop) ] Level 5: client.py:403: _reset: Reseting the client
39: [ Thread-3 (zk_loop) ] Level 5: connection.py:625: _connect_attempt: Connecting
39: [ Thread-3 (zk_loop) ] Level 5: connection.py:625: …
> Fix possible endless wait in stop() after AUTH_FAILED error

- .readthedocs.yaml
- constraints.txt
- docs/conf.py
- setup.cfg
Fixes #699 
Configure readthedocs documentation build directly in the project.
- use `.readthedocs.yaml`
- Include sphinx-autodoc-typehints
No
> chore(core): Fix documentation build

- .coveragerc
This fixes the `coverage` configuration that is wrongly giving a test coverage for the `tests` and `testing` folders and ends up "blocking" PR because of `codecov`.
- add `.coveragerc` file and exclude `tests` and `testing` folder all together
No, only good stuff here.
> fix(testing): add `.coveragerc`

- .github/workflows/testing.yml
- tox.ini
There is no need to perform the non-working `codecov` step via `tox` since we now have a Github Actions step that performs it.
- update `tox.ini` and remove `codecov` related stuff
- update GA `testing.yml` to remove `codecov` from matrix
Nah.
> feat(ci): remove `codecov` step from `tox` since performed in GA

- .github/workflows/testing.yml
- kazoo/handlers/utils.py
- kazoo/recipe/lock.py
- kazoo/testing/common.py
- kazoo/tests/test_cache.py
- kazoo/tests/test_eventlet_handler.py
- kazoo/tests/test_gevent_handler.py
- kazoo/tests/test_hosts.py
- kazoo/tests/test_selectors_select.py
- kazoo/tests/test_threading_handler.py
- kazoo/tests/util.py
- tox.ini
Fixes https://github.com/python-zk/kazoo/issues/679
This fixes an issue with the Windows platform that appeared in the latest 2.9.0 release. This also adds a very basic testing for the Windows platform (only 1 job, for the latest version of Python and the latest version of ZK).
- remove the `os.fstat(fd)` check that is invalid on Windows platform
- adjust `test_selector_select` test
- add a single job to test Windows platform (`gevent` seems broken on Windows so... skipped it): only 1 job because I don't feel like we need to re-test every version of Python/ZK for Windows
Nah.
> fix(core): fix for Windows platform

- .github/workflows/testing.yml
- kazoo/testing/common.py
- kazoo/testing/harness.py
- kazoo/tests/test_client.py
- setup.cfg
This adds a simple SSL test along with the framework for running
the test Zookeeper in a mode where it listens on both SSL and
non-SSL ports.
This is based on earlier work in #619.
> test: add SSL test

- .github/workflows/release.yml
- .github/workflows/testing.yml
- setup.cfg
Fixes #708 
[Python 3.7 is EOL since last year, Python 3.11 and Python 3.12 are here now.](https://devguide.python.org/versions/)
[ZK 3.6 is EOL since end of 2022 and ZK 3.9 is here.](https://zookeeper.apache.org/releases.html)
- drop Python 3.7 from testing
- add Python 3.11 and 3.12 to testing
- drop ZK 3.4 and 3.5
- add ZK 3.8 and 3.9
No.
> test: update Python and ZK in testing suite

- constraints.txt
- pyproject.toml
- setup.cfg
It's difficult to reproduce, but I've seen the github actions test suite take more than 6 hours. Having a timeout set will allow us to get some sort of useful debug information instead of having github actions kill it off before we can analyze anything.
- Do not allow any one unit test to take more than an hour. If it takes longer than an hour, kill it off and print some basic debug info (e.g. a stack trace of all/most frames).
- Enable color pytest output to make pytest easier to read in general.
No -- this is intended to help debug the test suite.
> chore: add a per test 3min timeout and enable color output

- kazoo/exceptions.py
Sync'd up to Zookeeper 3.9.2 error codes.
Server errors with missing error codes are handled poorly and result in connection close.
- Add definition for all know error codes as of Zookeeper 3.9.2
No.
> fix(core): Add missing Zookeeper exceptions codes

- kazoo/handlers/utils.py
- kazoo/protocol/connection.py
- kazoo/recipe/watchers.py
- kazoo/retry.py
- kazoo/tests/util.py
Fixes #722
`time.time()` is subject to changes in system local time and can trigger unexpected behavior. Prefer the use of `time.monotonic` instead of `time.time` since we are not making use of the actual time, only an amount of time elapsed.
- replace use of `time.time()` with `time.monotonic()`
No
> fix(core): prefer use of `time.monotonic`

- ensure-zookeeper-env.sh
So that we can perform testing again and better understand when this step fails.
So that ZK can be downloaded again during testing suite.
- display a little more information when the step fails
- follow http redirect
- use https mirror
No
> fix(testing): follow http redirect and use https mirror

- kazoo/tests/test_lock.py
See test failure https://github.com/python-zk/kazoo/actions/runs/8116444130/job/22206401448?pr=744
```python
for contender in ("reader", "writer"):
thread, event = contender_bits[contender]
with self.condition:
while not self.active_thread:
self.condition.wait()
>               assert self.active_thread == contender
E               AssertionError: assert 'writer' == 'reader'
E                 - reader
E                 + writer
kazoo/tests/test_lock.py:515: AssertionError
```
`test_rw_lock` is creating 2 threads (`reader` and `writer`) and, after being started, it is expected that `reader` is a contender before `writer`. In some busy systems (like the CI... it's always the CI!) this may not be true and lead to the test failure because `writer` can be a contender before `reader`. This …
> fix(test): avoid racy reader vs writer contender in `test_rw_lock`

- .readthedocs.yaml
I noticed this because `3.7` is EOL'd by upstream, plus `24.04` will be released later this month (although may take RTD a bit longer to pull it in).
Looking at [the docs](https://docs.readthedocs.io/en/stable/config-file/v2.html), there's a `latest` variant for both.
It comes with a warning that using latest may unexpectedly break builds if the project isn't compatible... But I think for our use case the odds that it will break are extremely low (and in fact we'd want to know it's broken so we could fix it!) Plus if it starts breaking, it's not hard to temp pin it to an older version.
So all-in-all, both lower maintenance and faster realization of breakage if we default to latest on both of these.
> chore(docs): Default ReadTheDocs to Ubuntu / Python `latest`

- kazoo/client.py
- kazoo/handlers/utils.py
- kazoo/protocol/connection.py
- kazoo/tests/test_utils.py
Fixes #754
Supports SNI
Add server_hostname to the wrap call
No
> Added support for SNI

- kazoo/retry.py
- kazoo/tests/test_retry.py
Make sure the number of attempts matches the `max_retry` parameter. Add unit tests to that effect.
So that users can precisely control the number of retries
- Move the location of the attempt increase to before the check against `max_try` so we don't end up calling `max_tries + 1` times the function.
No, it shouldn't.
> fix(core): Proper retry count in KazooRetry

- kazoo/client.py
- kazoo/exceptions.py
- kazoo/protocol/connection.py
- kazoo/recipe/lock.py
- kazoo/testing/common.py
- kazoo/tests/test_eventlet_handler.py
- kazoo/tests/test_gevent_handler.py
- kazoo/tests/test_retry.py
- kazoo/tests/test_threading_handler.py
To standardize spelling and create order
Fixes some typos
> refactor(python): fix spelling
